//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.241.0.
namespace EKAER.Schema.Common
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("UnloadReporterType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum UnloadReporterType
    {
        
        /// <summary>
        /// <para>A bejelentő jelentheti csak be a lerakodást!</para>
        /// </summary>
        S,
        
        /// <summary>
        /// <para>A bejelentő és a címzett (Destination adatoknál megadott fél) is lejelentheti a lerakodást!</para>
        /// </summary>
        D,
    }
    
    /// <summary>
    /// <para>Trade card státuszai. A státuszoknak sorrendisége van, meg van határozva hogy melyik státuszból melyikbe lehet csak lépni!</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("TradeCardStatusType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum TradeCardStatusType
    {

        /// <summary>
        /// <para>Prepare. Létrehozás után kerül ebbe a státuszba, amikor még csak tervezi a fuvart az ügyfél. Ebből a státuszból S-be lehet állítani!</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("P")]
        Prepare,

        /// <summary>
        /// <para>Start, On route, under delivery, it is on it's way. Amikor felpakolták a járművet és elindult, úton van! Abből a státuszból F-be lehet váltani.</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("S")]
        Start,

        /// <summary>
        /// <para>Finalized, unloaded. Amikor megérkezett a kirakodási helyre és lepakolták a szállítmányt. Ez a végső státusz itt van vége az életciklusnak. Ebből a státuszból nem lehet másik státuszba állítani.</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("F")]
        Finalized,

        /// <summary>
        /// <para>Inactive. Amikor nem véglegesedik megadott időn belül.</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("I")]
        Inactive,

        /// <summary>
        /// <para>Deleted. Törölt státusz, csak P-ből kerülhet ide. Más státuszokból az I-be léphet csak!</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("D")]
        Deleted,
    }
    
    /// <summary>
    /// <para>E: Export, I: Import, D:Domestic. A fuvar jellegét mutatja</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("TradeType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum TradeType
    {

        /// <summary>
        /// <para>Export</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("E")]
        Export,

        /// <summary>
        /// <para>Domestic</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("D")]
        Domestic,

        /// <summary>
        /// <para>Import</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("I")]
        Import,
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("TradeReasonType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum TradeReason
    {

        /// <summary>
        /// <para>Termék értékesítés / beszerzés</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("S")]
        Sale,

        /// <summary>
        /// <para>Saját tulajdonú termék - Törvény változás miatt kivezetve.</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("A")]
        Own,

        /// <summary>
        /// <para>Bérmunka</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("W")]
        Work,

        /// <summary>
        /// <para>Egyéb</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("O")]
        Other,
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("TradeCardType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum TradeCardType
    {
        
        /// <summary>
        /// <para>Simple, egyszerüsített bevallás</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("S")]
        Simple,

        /// <summary>
        /// <para>Normal, Normál adattartalmú bevallás</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("N")]
        Normal,
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("RecordStateType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum RecordStateType
    {

        /// <summary>
        /// <para>O: Original rekord, még nem lett módosítva</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("O")]
        Original,

        /// <summary>
        /// <para>M: Modified, már lett módosítva a rekord, van előélete</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("M")]
        Modified,

        /// <summary>
        /// <para>D: Deleted. Logikailag törölve lett!</para>
        /// </summary>
        [System.Xml.Serialization.XmlEnum("D")]
        Deleted,
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("FunctionCodeType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum FunctionCodeType
    {
        
        /// <summary>
        /// <para>OK</para>
        /// </summary>
        OK,
        
        /// <summary>
        /// <para>Warning</para>
        /// </summary>
        WARNING,
        
        /// <summary>
        /// <para>Error</para>
        /// </summary>
        ERROR,
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("ReasonCodeType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum ReasonCodeType
    {
        
        /// <summary>
        /// <para>Sikeres!</para>
        /// </summary>
        SUCCESS,
        
        /// <summary>
        /// <para>Általános / nem lekezelt -pl. technikai jellegű- hiba a feldolgozás során!</para>
        /// </summary>
        OPERATION_FAILED,
        
        /// <summary>
        /// <para>Érvénytelen adatok a kérésben!</para>
        /// </summary>
        INVALID_INPUT,
        
        /// <summary>
        /// <para>Kérés nem értelmezhető, érvénytelen request!</para>
        /// </summary>
        INVALID_REQUEST,
        
        /// <summary>
        /// <para>Kérés fejléc nem értelmezhető, érvénytelen request header!</para>
        /// </summary>
        INVALID_REQUEST_HEADERS,
        
        /// <summary>
        /// <para>A kért csomag verzió még nem létezik!</para>
        /// </summary>
        UNKNOWN_PACKAGE_VERSION,
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("BasicHeaderType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicPackageQueryRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicPackageQueryResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Fault))]
    public partial class BasicHeaderType
    {
        
        /// <summary>
        /// <para>A kérés azonosítója, minden request-nél más</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("requestId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RequestId { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _version = "1.0";
        
        /// <summary>
        /// <para>A request verziószáma, a request struktúra verziója</para>
        /// <para xml:lang="en">Minimum length: 3. Maximum length: 6.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,2}\.[0-9]{1,3}.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("1.0")]
        [System.Xml.Serialization.XmlAttributeAttribute("version", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Version
        {
            get
            {
                return this._version;
            }
            set
            {
                this._version = value;
            }
        }
        
        /// <summary>
        /// <para>A kérés keletkezésének ideje</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("timestamp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime Timestamp { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("BaseResultType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public partial class BaseResultType
    {
        
        /// <summary>
        /// <para>Sikeresség: SUCCESS, hiba ERROR, vagy WARNING</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("funcCode", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
        public FunctionCodeType FuncCode { get; set; }
        
        /// <summary>
        /// <para>Végrehajtási eredmény kódja!</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("reasonCode", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
        public ReasonCodeType ReasonCode { get; set; }
        
        /// <summary>
        /// <para>A végrehajtással kapcsolatos szöveges leírás ha szükséges. Általában akkor van töltve ha a funcCode nem SUCCESS</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("msg", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
        public string Msg { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("BasicRequestType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicPackageQueryRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicPackageQueryResponseType))]
    public partial class BasicRequestType : BasicHeaderType
    {
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("BasicResponseType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Fault))]
    public partial class BasicResponseType : BasicHeaderType
    {
        
        /// <summary>
        /// <para>Válasz sikeresség, eredmény adatok!</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("result", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
        public BaseResultType Result { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("BasicPackageQueryRequestType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public partial class BasicPackageQueryRequestType : BasicRequestType
    {
        
        /// <summary>
        /// <para>A lekérdezett csomag sorszáma</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("packageNumber", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
        public decimal PackageNumber { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("BasicPackageQueryResponseType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public partial class BasicPackageQueryResponseType : BasicRequestType
    {
        
        /// <summary>
        /// <para>A lekérdezett csomag sorszáma</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("packageNumber", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
        public decimal PackageNumber { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("AuditDetailsType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public partial class AuditDetailsType
    {
        
        /// <summary>
        /// <para>Módosítás időpontja</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("modDate", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common", DataType="dateTime")]
        public System.DateTime ModDate { get; set; }
        
        /// <summary>
        /// <para>Rekord állapota: A : active. I: Inactive</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("recordState", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
        public RecordStateType RecordState { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("BasicJournaledRecordType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public partial class BasicJournaledRecordType
    {
        
        /// <summary>
        /// <para>A módosításkövetett rekord rekord audit mezői!</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("auditDetails", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
        public AuditDetailsType AuditDetails { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Id { get; set; }
    }
    
    /// <summary>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("GPSCoordType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public partial class GPSCoordType
    {
        
        /// <summary>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 14.</para>
        /// <para xml:lang="en">Maximum exclusive value: 9999.99999999999999.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("latitude", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
        public decimal Latitude { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 14.</para>
        /// <para xml:lang="en">Maximum exclusive value: 9999.99999999999999.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("longitude", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
        public decimal Longitude { get; set; }
    }
    
    /// <summary>
    /// <para>Hiba esetén ilyen fault választ ada a server! result részen a hiba pontosabb definiálásával!</para>
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.241.0")]
    [System.Xml.Serialization.XmlTypeAttribute("fault", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Xml.Serialization.XmlRootAttribute("fault", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public partial class Fault : BasicResponseType
    {
    }
}
